Map<String, String> termDetails = {
  'Pratishyaya': 'Categories: Respiratory, Fever\n\n'
      'Symptoms: Runny nose, Sneezing, Cough\n\n'
      'Precautions: Stay hydrated, Rest, Avoid exposure to cold\n\n'
      'Cure: For common cold, you can try a home remedy by mixing turmeric in warm milk. Turmeric has anti-inflammatory properties and can help relieve symptoms. Additionally, rest, plenty of fluids, and over-the-counter cold medications are recommended.\n\n'
      'Ayurvedic Herbs: Tulsi, Ginger\n\n'
      'Formulations: Kadha, Chyawanprash\n\n'
      'Synonyms: Jvara\n\n'
      'Pharmacological Properties: Rasa - Katu, Guna - Ruksha, Virya - Ushna, Vipaka - Katu',
  'Sannipata Jvara': 'Categories: Respiratory, Fever\n\n'
      'Symptoms: Fever, Body aches, Fatigue\n\n'
      'Precautions: Bed rest, Stay hydrated\n\n'
      'Cure: In case of influenza, bed rest, and staying hydrated are crucial. You can also try Ayurvedic herbs like Ashwagandha and Echinacea. Formulations like Amritarishta and Guduchi powder may provide relief. Antiviral medications like Oseltamivir and Zanamivir may be prescribed.\n\n'
      'Ayurvedic Herbs: Ashwagandha, Echinacea\n\n'
      'Formulations: Amritarishta, Guduchi powder\n\n'
      'Synonyms: Jvara\n\n'
      'Pharmacological Properties: Rasa - Tikta, Guna - Laghu, Virya - Ushna, Vipaka - Madhura',
  'Anantavata': 'Categories: Neurological, Headache\n\n'
      'Symptoms: Severe headache, Nausea, Sensitivity to light and sound\n\n'
      'Precautions: Avoid triggers like stress and certain foods, Maintain a regular sleep schedule\n\n'
      'Cure: Migraine can be managed by avoiding triggers, maintaining a regular sleep schedule, and practicing relaxation techniques. Over-the-counter pain relievers like ibuprofen and acetaminophen can help alleviate symptoms. Ayurvedic herbs like Brahmi and Shankhpushpi may also provide relief.\n\n'
      'Ayurvedic Herbs: Brahmi, Shankhpushpi\n\n'
      'Formulations: Sarivaarishta, Dashmoolarishta\n\n'
      'Synonyms: Shirahshoola\n\n'
      'Pharmacological Properties: Rasa - Tikta, Guna - Laghu, Virya - Sheeta, Vipaka - Katu',
  'Pinasa': 'Categories: Respiratory, Fever\n\n'
      'Symptoms: Congestion, Sneezing, Headache\n\n'
      'Precautions: Steam inhalation, Stay hydrated, Rest\n\n'
      'Cure: Pinasa can be relieved by steam inhalation, staying hydrated, and getting plenty of rest. Ayurvedic herbs like Eucalyptus and Peppermint may provide relief. Formulations like Anu Taila and Sitopaladi churna may be beneficial.\n\n'
      'Ayurvedic Herbs: Eucalyptus, Peppermint\n\n'
      'Formulations: Anu Taila, Sitopaladi churna\n\n'
      'Synonyms: Jvara\n\n'
      'Pharmacological Properties: Rasa - Tikta, Guna - Laghu, Virya - Ushna, Vipaka - Katu',
  'Jvara': 'Categories: General\n\n'
      'Symptoms: Fever, Malaise, Sweating\n\n'
      'Precautions: Rest, Stay hydrated, Monitor temperature\n\n'
      'Cure: Jvara (fever) can be managed by getting plenty of rest, staying hydrated, and monitoring body temperature. Over-the-counter antipyretic medications like Acetaminophen and Ibuprofen may be used. Ayurvedic herbs like Tulsi and Ginger may also be beneficial.\n\n'
      'Ayurvedic Herbs: Tulsi, Ginger\n\n'
      'Formulations: Tribhuvankirti Ras, Sudarshan Churna\n\n'
      'Synonyms: Jvara\n\n'
      'Pharmacological Properties: Rasa - Katu, Guna - Laghu, Virya - Ushna, Vipaka - Katu',
  'Madhumeha': 'Categories: Metabolic, Endocrine\n\n'
      'Symptoms: Frequent urination, Increased thirst, Unexplained weight loss\n\n'
      'Precautions: Follow a balanced diet, Exercise regularly, Monitor blood sugar levels\n\n'
      'Cure: Diabetes is a chronic condition that requires lifelong management. It can be controlled through lifestyle modifications such as following a balanced diet, exercising regularly, and monitoring blood sugar levels. Medications like metformin and insulin may be prescribed. Ayurvedic herbs like Gurmar and Vijaysar may also help regulate blood sugar levels.\n\n'
      'Ayurvedic Herbs: Gurmar, Vijaysar\n\n'
      'Formulations: Chandraprabha Vati, Nishamalaki Churna\n\n'
      'Synonyms: Prameha\n\n'
      'Pharmacological Properties: Rasa - Tikta, Guna - Laghu, Virya - Sheeta, Vipaka - Katu',
  'Raktagata Vata': 'Categories: Cardiovascular\n\n'
      'Symptoms: High blood pressure, Headaches, Dizziness\n\n'
      'Precautions: Maintain a healthy weight, Reduce sodium intake, Exercise regularly\n\n'
      'Cure: Hypertension can be managed through lifestyle modifications such as maintaining a healthy weight, reducing sodium intake, and exercising regularly. Medications like diuretics, beta-blockers, and ACE inhibitors may be prescribed. Ayurvedic herbs like Arjuna and Ashwagandha may also help regulate blood pressure.\n\n'
      'Ayurvedic Herbs: Arjuna, Ashwagandha\n\n'
      'Formulations: Sarpagandha Ghan Vati, Mukta Vati\n\n'
      'Synonyms: Raktagata Vata\n\n'
      'Pharmacological Properties: Rasa - Katu, Guna - Laghu, Virya - Sheeta, Vipaka - Katu',
  'Anidra': 'Categories: Sleep\n\n'
      'Symptoms: Difficulty falling asleep, Difficulty staying asleep, Daytime sleepiness\n\n'
      'Precautions: Establish a bedtime routine, Create a sleep-friendly environment, Avoid caffeine and electronic devices before bed\n\n'
      'Cure: Insomnia can be managed through good sleep hygiene practices. Establishing a bedtime routine, creating a sleep-friendly environment, and avoiding caffeine and electronic devices before bed can help improve sleep quality. Ayurvedic herbs like Jatamansi and Ashwagandha may also promote better sleep.\n\n'
      'Ayurvedic Herbs: Jatamansi, Ashwagandha\n\n'
      'Formulations: Brahmi Ghrita, Saraswatarishta\n\n'
      'Synonyms: Nidranasha\n\n'
      'Pharmacological Properties: Rasa - Tikta, Guna - Laghu, Virya - Sheeta, Vipaka - Katu',
  'Amavata': 'Categories: Musculoskeletal\n\n'
      'Symptoms: Joint pain, Swelling, Stiffness\n\n'
      'Precautions: Regular exercise, Hot and cold compress, Medications\n\n'
      'Cure: Disease-modifying antirheumatic drugs (DMARDs) and NSAIDs are recommended for managing rheumatoid arthritis.\n\n'
      'Drugs: Methotrexate, Ibuprofen\n\n'
      'Ayurvedic Herbs: Turmeric, Guggul\n\n'
      'Formulations: Yograj guggulu, Maharasnadi kwath\n\n'
      'Sources: Charaka Samhita, Ashtanga Hridaya\n\n'
      'Synonyms: Amavata\n\n'
      'Pharmacological Properties: Rasa - Tikta, Guna - Guru, Virya - Ushna, Vipaka - Katu',
  'Arbuda': 'Categories: Oncological\n\n'
      'Symptoms: Unexplained weight loss, Fatigue, Pain\n\n'
      'Precautions: Early detection, Chemotherapy, Radiation therapy\n\n'
      'Cure: Surgery, chemotherapy, and radiation therapy are recommended for managing cancer.\n\n'
      'Drugs: Cisplatin, Tamoxifen\n\n'
      'Ayurvedic Herbs: Ashwagandha, Tulsi\n\n'
      'Formulations: Kanchnar guggulu, Triphala churna\n\n'
      'Sources: Charaka Samhita, Sushruta Samhita\n\n'
      'Synonyms: Arbuda\n\n'
      'Pharmacological Properties: Rasa - Tikta, Guna - Guru, Virya - Ushna, Vipaka - Katu',
  "Smritibhramsha": 'Categories: Neurological\n\n'
      'Symptoms: Memory loss, Confusion, Personality changes\n\n'
      'Precautions: Cognitive therapy, Supportive care, Medications\n\n'
      "Cure: Medications for cognitive symptoms and supportive care are recommended for managing Alzheimer's disease.\n\n"
      'Drugs: Donepezil, Memantine\n\n'
      'Ayurvedic Herbs: Brahmi, Ashwagandha\n\n'
      'Formulations: Mandukaparni ghrita, Brahmi vati\n\n'
      'Sources: Charaka Samhita, Ashtanga Hridaya\n\n'
      'Synonyms: Smritibhramsha\n\n'
      'Pharmacological Properties: Rasa - Madhura, Guna - Snigdha, Virya - Sheeta, Vipaka - Madhura',
  'Asthi-Majja Gata Vata': 'Categories: Musculoskeletal\n\n'
      'Symptoms: Bone pain, Fractures, Loss of height\n\n'
      'Precautions: Calcium and vitamin D supplements, Weight-bearing exercises, Medications\n\n'
      'Cure: Calcium and vitamin D supplements, bisphosphonates are recommended for managing osteoporosis.\n\n'
      'Drugs: Alendronate, Calcium supplements\n\n'
      'Ayurvedic Herbs: Shatavari, Arjuna\n\n'
      'Formulations: Asthiposhak tablet, Praval pishti\n\n'
      'Sources: Charaka Samhita, Sushruta Samhita\n\n'
      'Synonyms: Asthi-Majja Gata Vata\n\n'
      'Pharmacological Properties: Rasa - Madhura, Guna - Snigdha, Virya - Sheeta, Vipaka - Madhura',
  'Tamaka Shwasa': 'Categories: Respiratory\n\n'
      'Symptoms: Shortness of breath, Wheezing, Chest tightness\n\n'
      'Precautions: Inhaled corticosteroids, Bronchodilators, Avoid triggers\n\n'
      'Cure: Bronchodilators, inhaled corticosteroids are recommended for managing asthma.\n\n'
      'Drugs: Albuterol, Fluticasone\n\n'
      'Ayurvedic Herbs: Vasaka, Licorice\n\n'
      'Formulations: Sitopaladi churna, Swasari ras\n\n'
      'Sources: Charaka Samhita, Ashtanga Hridaya\n\n'
      'Synonyms: Tamaka Shwasa\n\n'
      'Pharmacological Properties: Rasa - Katu, Guna - Laghu, Virya - Ushna, Vipaka - Katu',
  'Amlapitta': 'Categories: Gastrointestinal\n\n'
      'Symptoms: Heartburn, Regurgitation, Chest pain\n\n'
      'Precautions: Antacids, Proton pump inhibitors, Avoid acidic foods\n\n'
      'Cure: Antacids, proton pump inhibitors are recommended for managing GERD.\n\n'
      'Drugs: Omeprazole, Ranitidine\n\n'
      'Ayurvedic Herbs: Aloe vera, Licorice\n\n'
      'Formulations: Avipattikar churna, Kamdudha ras\n\n'
      'Sources: Charaka Samhita, Sushruta Samhita\n\n'
      'Synonyms: Amlapitta\n\n'
      'Pharmacological Properties: Rasa - Tikta, Guna - Laghu, Virya - Ushna, Vipaka - Katu',
  'Vrikka Daurbalya': 'Categories: Renal\n\n'
      'Symptoms: Fatigue, Swelling, Shortness of breath\n\n'
      'Precautions: Low-salt diet, Medication adherence, Regular exercise\n\n'
      'Cure: Management of underlying causes, dialysis, kidney transplant\n\n'
      'Drugs: Angiotensin-converting enzyme (ACE) inhibitors, Angiotensin II receptor blockers (ARBs)\n\n'
      'Ayurvedic Herbs: Punarnava, Gokshura\n\n'
      'Formulations: Chandraprabha Vati, Punarnavadi Kwath\n\n'
      'Sources: Charaka Samhita, Sushruta Samhita\n\n'
      'Synonyms: Vrikka Kshaya\n\n'
      'Pharmacological Properties: Rasa - Tikta, Guna - Laghu, Virya - Ushna, Vipaka - Katu',
  'Vicharchika': 'Categories: Dermatological\n\n'
      'Symptoms: Itching, Redness, Dry skin\n\n'
      'Precautions: Moisturize regularly, Avoid triggers, Use mild soaps\n\n'
      'Cure: Topical corticosteroids, immunosuppressants\n\n'
      'Drugs: Hydrocortisone cream, Tacrolimus ointment\n\n'
      'Ayurvedic Herbs: Neem, Turmeric\n\n'
      'Formulations: Mahamarichyadi Taila, Panchatikta Ghrita Guggulu\n\n'
      'Sources: Charaka Samhita, Sushruta Samhita\n\n'
      'Synonyms: Vicharchika\n\n'
      'Pharmacological Properties: Not specified',
  'Sidhma Kushtam': 'Categories: Dermatological\n\n'
      'Symptoms: Red, scaly patches, Itching, Joint pain\n\n'
      'Precautions: Moisturize, Avoid triggers, Sun exposure\n\n'
      'Cure: Topical treatments, phototherapy, systemic medications\n\n'
      'Drugs: Topical corticosteroids, Methotrexate\n\n'
      'Ayurvedic Herbs: Aloe vera, Neem\n\n'
      'Formulations: Kaishora Guggulu, Panchatikta Ghrita Guggulu\n\n'
      'Sources: Charaka Samhita, Sushruta Samhita\n\n'
      'Synonyms: Sidhma Kushtam\n\n'
      'Pharmacological Properties: Not specified',
  'Visuchika': 'Categories: Infectious\n\n'
      'Symptoms: Severe diarrhea, Vomiting, Dehydration\n\n'
      'Precautions: Oral rehydration therapy, Hygiene practices, Vaccination\n\n'
      'Cure: Rehydration, antibiotics in severe cases\n\n'
      'Drugs: Oral rehydration salts, Azithromycin\n\n'
      'Ayurvedic Herbs: Not specified\n\n'
      'Formulations: Not specified\n\n'
      'Sources: Charaka Samhita, Sushruta Samhita\n\n'
      'Synonyms: Visuchika\n\n'
      'Pharmacological Properties: Not specified',
  'Rajayakshma': 'Categories: Infectious\n\n'
      'Symptoms: Cough, Weight loss, Fever\n\n'
      'Precautions: Antibiotics, Isolation, Vaccination\n\n'
      'Cure: Antibiotics (Isoniazid, Rifampin, etc.), directly observed therapy (DOT)\n\n'
      'Drugs: Isoniazid, Rifampin\n\n'
      'Ayurvedic Herbs: Vasa, Tulsi\n\n'
      'Formulations: Swasakuthar Ras, Laxmi Vilas Ras\n\n'
      'Sources: Charaka Samhita, Sushruta Samhita\n\n'
      'Synonyms: Rajayakshma\n\n'
      'Pharmacological Properties: Not specified',
  "Kampavata": 'Categories: Neurological\n\n'
      'Symptoms: Tremors, Bradykinesia, Stiffness\n\n'
      'Precautions: Medication adherence, Physical therapy, Deep brain stimulation\n\n'
      'Cure: Management of symptoms with medications (levodopa, etc.), surgery in some cases\n\n'
      'Drugs: Levodopa, Ropinirole\n\n'
      'Ayurvedic Herbs: Ashwagandha, Mucuna pruriens\n\n'
      'Formulations: Maharasnadi Kwath, Brahmi Ghrita\n\n'
      'Sources: Charaka Samhita, Sushruta Samhita\n\n'
      'Synonyms: Kampavata\n\n'
      'Pharmacological Properties: Not specified',
  'Yakritpleeha Sotha': 'Categories: Hepatic\n\n'
      'Symptoms: Jaundice, Fatigue, Abdominal pain\n\n'
      'Precautions: Vaccination, Avoiding high-risk behaviors, Regular medical check-ups\n\n'
      'Cure: Antiviral medications, liver transplant in severe cases\n\n'
      'Drugs: Entecavir, Tenofovir\n\n'
      'Ayurvedic Herbs: Bhumyamalaki, Kutki\n\n'
      'Formulations: Arogyavardhini Vati, Liv.52\n\n'
      'Sources: Charaka Samhita, Sushruta Samhita\n\n'
      'Synonyms: Yakritpleeha Sotha\n\n'
      'Pharmacological Properties: Not specified',
  'Vatarakta': 'Categories: Rheumatological\n\n'
      'Symptoms: Joint pain, Swelling, Redness\n\n'
      'Precautions: Low-purine diet, Hydration, Medications\n\n'
      'Cure: Medications (NSAIDs, colchicine), lifestyle changes\n\n'
      'Drugs: Colchicine, Indomethacin\n\n'
      'Ayurvedic Herbs: Guduchi, Triphala\n\n'
      'Formulations: Punarnavadi Kwath, Kaishora Guggulu\n\n'
      'Sources: Charaka Samhita, Sushruta Samhita\n\n'
      'Synonyms: Vatarakta\n\n'
      'Pharmacological Properties: Not specified',
  'Yoni Dosha': 'Categories: Gynecological\n\n'
      'Symptoms: Pelvic pain, Painful periods, Infertility\n\n'
      'Precautions: Pain management, Hormone therapy, Surgery\n\n'
      'Cure: Surgery, hormone therapy\n\n'
      'Drugs: NSAIDs, Hormonal contraceptives\n\n'
      'Ayurvedic Herbs: Ashoka, Lodhra\n\n'
      'Formulations: Pushyanuga Churna, Chandraprabha Vati\n\n'
      'Sources: Charaka Samhita, Sushruta Samhita\n\n'
      'Synonyms: Yoni Dosha\n\n'
      'Pharmacological Properties: Not specified',
  'Rajaswala Dosha': 'Categories: Reproductive Health\n\n'
      'Symptoms: Irregular periods, Heavy bleeding, Painful cramps\n\n'
      'Precautions: Healthy lifestyle, Regular exercise, Stress management\n\n'
      'Cure: Hormonal therapy, lifestyle changes\n\n'
      'Drugs: Oral contraceptives, Nonsteroidal anti-inflammatory drugs (NSAIDs)\n\n'
      'Ayurvedic Herbs: Ashoka, Shatavari\n\n'
      'Formulations: Rajarajaeshwari Ras, Kumaryasava\n\n'
      'Sources: Charaka Samhita, Sushruta Samhita\n\n'
      'Synonyms: Rajaswala Dosha\n\n'
      'Pharmacological Properties: Rasa - Madhura, Guna - Snigdha, Virya - Shita, Vipaka - Madhura',
  'Granthsada Yonivyapad': 'Categories: Reproductive Health\n\n'
      'Symptoms: Irregular menstrual cycles, Excessive hair growth, Acne\n\n'
      'Precautions: Healthy diet, Regular exercise, Stress management\n\n'
      'Cure: Lifestyle modifications, hormonal therapy\n\n'
      'Drugs: Combined oral contraceptives, Anti-androgen medications\n\n'
      'Ayurvedic Herbs: Shatavari, Ashoka\n\n'
      'Formulations: Chandraprabha Vati, Kumaryasava\n\n'
      'Sources: Charaka Samhita, Sushruta Samhita\n\n'
      'Synonyms: Granthsada Yonivyapad\n\n'
      'Pharmacological Properties: Rasa - Madhura, Guna - Snigdha, Virya - Shita, Vipaka - Madhura',
  'Garbhasayagata Prameha': 'Categories: Obstetric\n\n'
      'Symptoms: High blood sugar during pregnancy\n\n'
      'Precautions: Balanced diet, Regular exercise, Monitoring blood sugar levels\n\n'
      'Cure: Dietary management, insulin therapy if necessary\n\n'
      'Drugs: Insulin\n\n'
      'Ayurvedic Herbs: Guduchi, Haritaki\n\n'
      'Formulations: Chandraprabha Vati, Amalaki Rasayana\n\n'
      'Sources: Charaka Samhita, Sushruta Samhita\n\n'
      'Synonyms: Garbhasayagata Prameha\n\n'
      'Pharmacological Properties: Rasa - Tikta, Guna - Laghu, Virya - Ushna, Vipaka - Katu',
  'Rajaswala Anta': 'Categories: Gynecological\n\n'
      'Symptoms: Hot flashes, Mood swings, Sleep disturbances\n\n'
      'Precautions: Hormone replacement therapy (HRT), Healthy lifestyle, Regular exercise\n\n'
      'Cure: Hormone replacement therapy, lifestyle modifications\n\n'
      'Drugs: Estrogen therapy, Selective serotonin reuptake inhibitors (SSRIs)\n\n'
      'Ayurvedic Herbs: Shatavari, Ashwagandha\n\n'
      'Formulations: Maha Yogaraj Guggulu, Dashamoola Arishta\n\n'
      'Sources: Charaka Samhita, Sushruta Samhita\n\n'
      'Synonyms: Rajaswala Anta\n\n'
      'Pharmacological Properties: Rasa - Madhura, Guna - Snigdha, Virya - Shita, Vipaka - Madhura',
  'Asthi-Majja Kshaya': 'Categories: Musculoskeletal\n\n'
      'Symptoms: Bone loss, Fractures\n\n'
      'Precautions: Calcium-rich diet, Weight-bearing exercises, Bone density screenings\n\n'
      'Cure: Calcium and Vitamin D supplements, lifestyle modifications\n\n'
      'Drugs: Calcium supplements, Vitamin D supplements\n\n'
      'Ayurvedic Herbs: Arjuna, Ashwagandha\n\n'
      'Formulations: Asthi-Majja Kashaya, Punarnavadi Kwath\n\n'
      'Sources: Charaka Samhita, Sushruta Samhita\n\n'
      'Synonyms: Asthi-Majja Kshaya\n\n'
      'Pharmacological Properties: Rasa - Tikta, Guna - Laghu, Virya - Ushna, Vipaka - Katu',
  'Vata': 'Qualities: Dry, light, cold, rough, subtle, mobile.\n\n'
      'Elements: Ether (space) and Air.\n\n'
      'Functions: Governs all movement in the body, including nerve impulses, circulation, respiration, and elimination.\n\n',
  'Pitta': 'Qualities: Hot, sharp, light, oily, liquid, spreading.\n\n'
      'Elements: Fire and Water.\n\n'
      'Functions: Governs digestion, metabolism, and transformation of food into energy; regulates body temperature and hormonal balance.\n\n',
  'Kapha': 'Qualities: Heavy, cold, oily, smooth, dense, static.\n\n'
      'Elements: Earth and Water.\n\n'
      'Functions: Provides structure, stability, and lubrication; governs growth, strength, and immune function.\n\n',
};
